### PR TITLE
Tile by gid fix

### PR DESCRIPTION
**Pull request by supagu**
Patch to fix tileByGid which was returning the wrong tile as firstGid is a 1 based index.

This branch also includes change #25

### CODE REVIEW

**Comment by supagu** [comment]
Can we get this test re-run and then merged as I have made fixes to this

**Review by luanpotter — APPROVED** [review]
Wow, quite confusing that `firstGid` is 1 based but `localId` is not!

**Review by spydon — APPROVED** [review]

**Review by erickzanardo — APPROVED** [review]

**Comment by luanpotter** [comment]
I fixed the build; but this is actually breaking the tests now.

**Comment by luanpotter** [comment]
Seems at least one test is very clear on checking:

```dart
    test('returns an empty Tile if GID is 0', () {
      tile = map.tileByGid(0);
      expect(tile.isEmpty, isTrue);
    });
```

I  definitely do not know or remember the rationale there. Are you sure about this 1 vs 0 discrepancy?

**Comment by supagu** [comment]
According to this post:
https://discourse.mapeditor.org/t/option-to-export-tile-data-with-0-based-indexes/2672/2

We might need to check for 0 before subtracting 1.

**Comment by luanpotter** [comment]
I think they are both 1 based, by reading that thread:

> Indeed, global ID 0 is used for empty cells so the first tile in the first tileset always gets global ID 1.

0 always mean no tile. both for local and global. so I don't see why the conversion is necessary...

**Comment by luanpotter** [comment]
I tested this change with flame_tiled and it is totally correct. Go figure!

**Comment by luanpotter** [comment]
I merged this on the command line + the test fixes

**Comment by luanpotter** [comment]
actually, that was not the solution. after many more tests, I believe this is the real deal (the problem was something else):
https://github.com/flame-engine/tiled.dart/commit/cb08bc937f82a6ed42cb47fa9b526446ea8e9f76

**Pull request closed without merging**
